apiVersion: apps/v1
kind: Deployment
metadata:
  name: agenda-service-deployment
  namespace: myconf
spec:
  selector:
    matchLabels:
      app: agenda-service
  template:
    metadata:
      labels:
        app: agenda-service
        app.kubernetes.io/name: agenda-service
        app.kubernetes.io/part-of: agenda-service
    spec:
      containers:
      - name: agenda-service
        image: "dylanfeehan/conf-agenda:01979cd211aa38b61deac446c3426844341f84b4"
        imagePullPolicy: Always
        #resources:
          #limits:
            #memory: 512Mi
            #cpu: "1"
        env:
        - name: KAFKA_URL
          value: conference-kafka.myconf.svc.cluster.local:9092
        - name: REDIS_HOST
          value: conference-redis-master.myconf.svc.cluster.local
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: conference-redis
              key: redis-password
        - name: POD_NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName      
        #livenessProbe:
          #httpGet:
            #path: /health/liveness
            #port: 8080
        #readinessProbe:
          #httpGet:
            #path: /health/readiness
            #port: 8080
        ports:
        - containerPort: 8080
---
