name: buidl-and-publish-to-acr
on:
  #push:
  #branches:
  #- master
  workflow_dispatch:

jobs:
  register:
    name: Build image
    runs-on:
      ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
          #- id: setup-kub-test
          #run: |
          #mkdir ~/.kube/
          #touch ~/.kube/config
          #echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          #export KUBE_CONFIG=$HOME/.kube/config
          #kubectl get deployments -n myconf

      - name: Build app into image
        run: |
          sudo add-apt-repository ppa:cncf-buildpacks/pack-cli
          sudo apt-get update
          sudo apt-get install pack-cli
          pack build conf-agenda-app --buildpack paketo-buildpacks/go --builder paketobuildpacks/builder-jammy-base

      - name: Publish image to Dockerhub
        run: |
          docker login -u dylanfeehan -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          docker tag conf-agenda-app dylanfeehan/conf-agenda:${{ github.sha }}
          docker push dylanfeehan/conf-agenda:${{ github.sha }}
      
      #- id: deploy-image
        #run: |
          #sed -i.backup "s#dylerd.azurecr.io/aks-demo-app:.*#dylerd.azurecr.io/aks-demo-app:${{ github.sha }}#g" config/deployment.yml
          #kubectl --kubeconfig=$HOME/.kube/config apply -f deployment.yml
